# Generated by Django 2.2.4 on 2021-08-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('admin', '어드민'), ('user', '사용자')], default='user', max_length=8, verbose_name='등급'),
            preserve_default=False,
        ),
    ]
